apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
      - name: sa-task3
        image: almar98/sa-task3
        ports:
        - containerPort: 5000